BookKeeper-Client config to write ledger metadata with configured version (#2708)
### Motivation

We need a way to use old bookie which doesn't support metadata-version-3 and upgrade bookkeeper-client with latest version. Right now, bk-4.12 writes ledger metadata with version-3 which will not be supported by bookie and replicator and replicator fails with below error
```
2021-05-07.00:43:53.115 [main-EventThread] ERROR
                o.a.b.meta.AbstractZkLedgerManager   - Could not parse ledger metadata for ledger: 123456
java.io.IOException: Metadata version not compatible. Expected between 0 and 2, but got 3
        at org.apache.bookkeeper.client.LedgerMetadata.parseConfig(LedgerMetadata.java:465)
        at org.apache.bookkeeper.meta.AbstractZkLedgerManager$3.processResult(AbstractZkLedgerManager.java:414)
        at org.apache.bookkeeper.zookeeper.ZooKeeperClient$19$1.processResult(ZooKeeperClient.java:994)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:572)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:508)

```
So, until one upgrades the bookie version, allow bk-client to use the appropriate metadata version.