fix mailing-lists dead links (#3804)
### Motivation
Fix the mailing-lists.md dead links which cause Dead link checker failed.
There are some links looks like not stable, we can use new link to replace it.

CI filed link:https://github.com/apache/bookkeeper/actions/runs/4260370313/jobs/7413461899

```
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-user/
ERROR: 4 dead links found!
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-dev/
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-issues/
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-commits/

20 links checked.
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-user/ → Status: 0
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-dev/ → Status: 0
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-issues/ → Status: 0
[✖] http://mail-archives.apache.org/mod_mbox/bookkeeper-commits/ → Status: 0
```
### Changes
1. use new link to replace the dead links in mailing-lists.md.