Upgrade Netty to 4.1.94.Final (#3999)
### Motivation

OWASP dependency check fails because of CVE-2023-34462
```
Error:  netty-handler-4.1.93.Final.jar: CVE-2023-34462(8.8)
```

### Changes

Upgrade Netty to 4.1.94.Final
Release notes: https://netty.io/news/2023/06/19/4-1-94-Final.html