[fix] release resources hold by asyncStore (#65)
Descriptions of the changes in this PR:

### Motivation

If not releasing resources of failed store, new creating of the same store identifier will fail, mainly caused by RocksDBException, like below
```log
2019-03-07 21:39:05,137 - WARN  [io-write-scheduler-OrderedScheduler-31-0:ZkStorageContainerManager@281] - Failed to start storage container (6)
java.util.concurrent.CompletionException: org.apache.bookkeeper.statelib.api.exceptions.StateStoreException: org.rocksdb.RocksDBException: While lock file: /mnt/ssddir/cstream/ranges/ranges/000000000000000006/000000000000000001/000000000000000000/current/LOCK: No locks available
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.bookkeeper.statelib.impl.journal.AbstractStateStoreWithJournal.lambda$executeIO$16(AbstractStateStoreWithJournal.java:474)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.bookkeeper.statelib.api.exceptions.StateStoreException: org.rocksdb.RocksDBException: While lock file: /mnt/ssddir/cstream/ranges/ranges/000000000000000006/000000000000000001/000000000000000000/current/LOCK: No locks available
	at org.apache.bookkeeper.statelib.impl.kv.RocksdbKVStore.openRocksdb(RocksdbKVStore.java:334)
	at org.apache.bookkeeper.statelib.impl.kv.RocksdbKVStore.openLocalDB(RocksdbKVStore.java:298)
	at org.apache.bookkeeper.statelib.impl.kv.RocksdbKVStore.openRocksdb(RocksdbKVStore.java:288)
	at org.apache.bookkeeper.statelib.impl.kv.RocksdbKVStore.init(RocksdbKVStore.java:233)
	at org.apache.bookkeeper.statelib.impl.journal.AbstractStateStoreWithJournal.lambda$initializeLocalStore$5(AbstractStateStoreWithJournal.java:202)
	at org.apache.bookkeeper.statelib.impl.journal.AbstractStateStoreWithJournal.lambda$executeIO$16(AbstractStateStoreWithJournal.java:471)
	... 12 more
Caused by: org.rocksdb.RocksDBException: While lock file: /mnt/ssddir/cstream/ranges/ranges/000000000000000006/000000000000000001/000000000000000000/current/LOCK: No locks available
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:286)
	at org.apache.bookkeeper.statelib.impl.kv.RocksdbKVStore.openRocksdb(RocksdbKVStore.java:323)
	... 17 more
```
### Changes

add scStores to factory's instance variable;
release store when open fail;