Upgrade dependency-check-maven plugin to fix broken OWASP check (#3731)
* Upgrade dependency-check-maven plugin to fix broken OWASP check

- 7.4.4 includes fix for issue
      https://github.com/jeremylong/DependencyCheck/issues/5220

    Error:  org.owasp.dependencycheck.data.nvdcve.DatabaseException: Error updating 'CVE-2020-36569'
    org.owasp.dependencycheck.data.update.exception.UpdateException: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Error updating 'CVE-2020-36569'
    ...
    Caused by: org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "VERSIONENDEXCLUDING CHARACTER VARYING(60)": "'0.0.0-20160722212129-ac0cc4484ad4_before_v0.0.0-20200131131040-063a3fb69896' (75)"; SQL statement:

* Add suppressions related to snakeyaml

* Add more suppressions

* Upgrade to 8.0.2 version

* Add snakeyaml suppression