Fixed: DLCheckpointStore rethrows exceptions as FNFE but swallows the rootcause
DLCheckpointStore rethrows exceptions as FNFE but swallows the rootcause
Same as https://github.com/apache/bookkeeper/pull/2553 but for master branch

Descriptions of the changes in this PR:

added .initCause for the new FNFE exception to preserver it

### Motivation

got the
ERROR org.apache.bookkeeper.statelib.impl.rocksdb.checkpoint.RocksCheckpointer - Failed to restore rocksdb ...
java.io.FileNotFoundException: ..../metadata
without any additional info for the rootcause (other than stack pointing to the DLCheckpointStore)

DLCheckpointStore appears to re-throw exceptions as FNFE without preserving the rootcause

### Changes

added .initCause

Master Issue: #2552


Reviewers: Enrico Olivelli <eolivelli@gmail.com>

This closes #2555 from dlg99/master-fnfe